replicaCount: 1

image:
  repository: solidinvoice/solidinvoice
  pullPolicy: Always
  tag: "2.1.2"

nameOverride: "solidinvoice"
fullnameOverride: "solidinvoice"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: bootcamp-helm.zerofiltre.tech
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: bootcamp-helm-zerofiltre-ingress-cert
    hosts:
    - bootcamp-helm.zerofiltre.tech

resources:
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 250m
    memory: 100Mi

nodeSelector:
  dedicated: bootcamp

database:
  host: mariadb-svc
  port: 3306
  name: solidinvoicebootcamp
  user: solidinvoicebootcamp
  password: 12345678
  driver: pdo_mysql
  type: 5.5.5-10.7.7-MariaDB-1:10.7.7+maria~ubu2004
  locale: fr_FR