---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-base-pvc
  namespace: zerofiltre-bootcamp
  labels:
    dedicated: bootcamp
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: csi-cinder-high-speed
  volumeMode: Filesystem