apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: "{{ .Values.pvc.storage }}"
  accessModes:
  - "{{ .Values.pvc.accessModes }}"
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  volumeMode: Filesystem