apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.database.user | b64enc }}
  MARIADB_USER: {{ .Values.database.password | b64enc }}
  MARIADB_PASSWORD: {{ .Values.database.rootPassword | b64enc }}