---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: zerofiltre-bootcamp
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: U2VjcmV0Um9vdA==
  MARIADB_USER: c29saWRpbnZvaWNl
  MARIADB_PASSWORD: U2VjcmV0U29saWRpbnZvaWNl