{{- $fullName := include "solidinvoice.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "solidinvoice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "solidinvoice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "solidinvoice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: {{ printf "%s-secret-volume" $fullName }}
          mountPath: /opt/srv/config/env.php
          subPath: env.php  
      volumes: 
      - name: {{ printf "%s-secret-volume" $fullName }}
        secret:
          secretName: {{ $fullName }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
