apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solidinvoice.fullname" . }}
  labels:
    {{- include "solidinvoice.labels" . | nindent 4 }}
type: Opaque    
data:
  env.php: |
    {{ tpl (.Files.Get "env.yaml") . | b64enc }}