---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: solidinvoice-hpa
  namespace: zerofiltre-bootcamp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solidinvoice-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50