apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: solidinvoice-vpa
  namespace: zerofiltre-bootcamp
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solidinvoice-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "solidinvoice"
      minAllowed:
        cpu: "250m"
        memory: "100Mi"
      maxAllowed:
        cpu: "1"
        memory: "1Gi"