# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "gusztavvargadr/ubuntu-desktop"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
  end

  # Ubuntu Desktop.
  config.vm.define "ubuntu-2004" do |app|
    app.vm.hostname = "desktop"
    app.vm.network :private_network, ip: "192.168.56.10"
  end
end
